# uncompyle6 version 3.3.1
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.1 (default, Nov  6 2018, 18:46:03)
# [Clang 10.0.0 (clang-1000.11.45.5)]
# Embedded file name: /Users/quark/studia/zpp/new/utils/ConvertNER/NER_pwr_to_spacy.py
# Size of source mod 2**32: 1685 bytes
NER_pwr_to_spacy = {'person_nam':'PER',  'institution_nam':'ORG',
 'city_nam':'LOC',
 'person_last_nam':'PER',
 'person_first_nam':'PER',
 'document_nam':'MISC',
 'event_nam':'MISC',
 'organization_nam':'ORG',
 'country_nam':'LOC',
 'title_nam':'MISC',
 'band_nam':'ORG',
 'periodic_nam':'MISC',
 'company_nam':'ORG',
 'facility_nam':'ORG',
 'brand_nam':'ORG',
 'political_party_nam':'ORG',
 'road_nam':'LOC',
 'admin1_nam':'LOC',
 'person_add_nam':'PER',
 'software_nam':'MISC',
 'nation_nam':'MISC',
 'tech_nam':'MISC',
 'nam':'MISC',
 'treaty_nam':'MISC',
 'web_nam':'MISC',
 'admin2_nam':'LOC',
 'award_nam':'MISC',
 'continent_nam':'LOC',
 'astronomical_nam':'LOC',
 'media_nam':'ORG',
 'river_nam':'LOC',
 'currency_nam':'MISC',
 'toponym_nam':'LOC',
 'mountain_nam':'LOC',
 'historical_region_nam':'LOC',
 'district_nam':'LOC',
 'country_region_nam':'LOC',
 'subdivision_nam':'ORG',
 'admin3_nam':'LOC',
 'region_nam':'LOC',
 'square_nam':'LOC',
 'park_nam':'LOC',
 'island_nam':'LOC',
 'system_nam':'MISC',
 'www_nam':'MISC',
 'person_group_nam':'MISC',
 'license_nam':'MISC',
 'lake_nam':'LOC',
 'animal_nam':'MISC',
 'sea_nam':'LOC',
 'person_adj_nam':'PER',
 'bay_nam':'LOC',
 'peninsula_nam':'LOC',
 'conurbation_nam':'LOC',
 'vehicle_nam':'MISC',
 'organization_sub_nam':'ORG',
 'ocean_nam':'LOC',
 'cape_nam':'LOC'}
# okay decompiling NER_pwr_to_spacy.cpython-37.pyc
