# uncompyle6 version 3.3.1
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.1 (default, Nov  6 2018, 18:46:03) 
# [Clang 10.0.0 (clang-1000.11.45.5)]
# Embedded file name: /Users/quark/studia/zpp/new/utils/ConvertNER/NER_pwr_to_spacy.py
# Size of source mod 2**32: 1685 bytes
NER_pwr_to_spacy = {'person_nam':'PERSON',  'institution_nam':'ORG', 
 'city_nam':'GPE', 
 'person_last_nam':'PERSON', 
 'person_first_nam':'PERSON', 
 'document_nam':'WORK_OF_ART', 
 'event_nam':'EVENT', 
 'organization_nam':'ORG', 
 'country_nam':'GPE', 
 'title_nam':'WORK_OF_ART', 
 'band_nam':'ORG', 
 'periodic_nam':'PRODUCT', 
 'company_nam':'ORG', 
 'facility_nam':'ORG', 
 'brand_nam':'ORG', 
 'political_party_nam':'NORP', 
 'road_nam':'FAC', 
 'admin1_nam':'GPE', 
 'person_add_nam':'PERSON', 
 'software_nam':'PRODUCT', 
 'nation_nam':'GPE', 
 'tech_nam':'PRODUCT', 
 'nam':'PERSON', 
 'treaty_nam':'LAW', 
 'web_nam':'PRODUCT', 
 'admin2_nam':'GPE', 
 'award_nam':'EVENT', 
 'continent_nam':'LOC', 
 'astronomical_nam':'LOC', 
 'media_nam':'ORG', 
 'river_nam':'LOC', 
 'currency_nam':'MONEY', 
 'toponym_nam':'LOC', 
 'mountain_nam':'LOC', 
 'historical_region_nam':'LOC', 
 'district_nam':'LOC', 
 'country_region_nam':'GPE', 
 'subdivision_nam':'ORG', 
 'admin3_nam':'GPE', 
 'region_nam':'LOC', 
 'square_nam':'LOC', 
 'park_nam':'LOC', 
 'island_nam':'LOC', 
 'system_nam':'PRODUCT', 
 'www_nam':'PRODUCT', 
 'person_group_nam':'NORP', 
 'license_nam':'LAW', 
 'lake_nam':'LOC', 
 'animal_nam':'MISC', 
 'sea_nam':'LOC', 
 'person_adj_nam':'PERSON', 
 'bay_nam':'LOC', 
 'peninsula_nam':'LOC', 
 'conurbation_nam':'LOC', 
 'vehicle_nam':'PRODUCT', 
 'organization_sub_nam':'ORG', 
 'ocean_nam':'LOC', 
 'cape_nam':'LOC'}
# okay decompiling NER_pwr_to_spacy.cpython-37.pyc
